service: simple-crud-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs22.x
  stage: ${opt:stage, dev}
  region: ${opt:region, us-east-1}
  environment:
    TABLE_NAME: ${self:service}-table-${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:Scan
        - dynamodb:DeleteItem
        - dynamodb:UpdateItem
      Resource:
        - arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.TABLE_NAME}

functions:
  create:
    handler: handler.create
    events:
      - httpApi:
          path: /items
          method: post

  list:
    handler: handler.list
    events:
      - httpApi:
          path: /items
          method: get

  get:
    handler: handler.get
    events:
      - httpApi:
          path: /items/{id}
          method: get
  update:
    handler: handler.update
    events:
      - httpApi:
          path: /items/{id}
          method: put

  delete:
    handler: handler.remove
    events:
      - httpApi:
          path: /items/{id}
          method: delete

resources:
  Resources:
    ItemsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
