name: Deploy to AWS

on:
  push:
    branches:
      - main   # or master, whichever you use

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Serverless
        run: npm install -g serverless

      - name: Install dependencies
        run: npm install

      - name: Deploy with Serverless
        run: sls deploy --stage dev --region us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
